### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

### ISSUE THREAD

**Issue by meanstack9716** [Lg0gs/react-native-tiktok#6]
WARNING:: The specified Android SDK Build Tools version (29.0.2) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '29.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
16 actionable tasks: 2 executed, 14 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.bytedance.ies.ugc.aweme:open-sdk:0.0.1.5.
     Searched in the following locations:
       - file:/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/react-native/android/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
       - file:/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/jsc-android/dist/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
       - https://repo.maven.apache.org/maven2/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
       - https://dl.google.com/dl/android/maven2/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
       - https://www.jitpack.io/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
     Required by:
         project :app > project :react-native-tiktok

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.bytedance.ies.ugc.aweme:open-sdk:0.0.1.5.
     Searched in the following locations:
       - file:/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/react-native/android/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
       - file:/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/jsc-android/dist/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
       - https://repo.maven.apache.org/maven2/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
       - https://dl.google.com/dl/android/maven2/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
       - https://www.jitpack.io/com/bytedance/ies/ugc/aweme/open-sdk/0.0.1.5/open-sdk-0.0.1.5.pom
     Required by:
         project :app > project :react-native-tiktok

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

    at makeError (/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/execa/index.js:174:9)
    at /Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/@react-native-community/cli/build/index.js:192:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Lg0gs** [comment]
@meanstack9716 
Upgraded to version 30. Can you try again?

**Comment by meanstack9716** [comment]
@Lg0gs Hi, thank you for reply, yes the above issue is fixed but not getting another issue

info JS server already running.
info Installing the app...
debug Running command "cd android && ./gradlew app:installDebug -PreactNativeDevServerPort=8081"
> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
16 actionable tasks: 2 executed, 14 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.bytedance.ies.ugc.aweme:opensdk-oversea-external:0.2.0.2.
     Searched in the following locations:
       - file:/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/react-native/android/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
       - file:/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/jsc-android/dist/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
       - https://repo.maven.apache.org/maven2/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
       - https://dl.google.com/dl/android/maven2/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
       - https://www.jitpack.io/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
     Required by:
         project :app > project :react-native-tiktok

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.bytedance.ies.ugc.aweme:opensdk-oversea-external:0.2.0.2.
     Searched in the following locations:
       - file:/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/react-native/android/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
       - file:/Users/yuvrajsingh/Projects/innovation/upwork/loveTheIdea/omniApp/heatmap/node_modules/jsc-android/dist/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
       - https://repo.maven.apache.org/maven2/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
       - https://dl.google.com/dl/android/maven2/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
       - https://www.jitpack.io/com/bytedance/ies/ugc/aweme/opensdk-oversea-external/0.2.0.2/opensdk-oversea-external-0.2.0.2.pom
     Required by:
         project :app > project :react-native-tiktok

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by meanstack9716** [comment]
@Lg0gs Any updates, I need this library

**Comment by Lg0gs** [comment]
@meanstack9716 
Updated with a new version. Can you try?

**Comment by meanstack9716** [comment]
@Lg0gs thank you for the answer.
But it still gives lots of errors to me. Not the old one.
Please create a new react native app and try to run it, you can see errors.

**Comment by islamashraful** [comment]
@meanstack9716 For your problem, it doesn't look like you have a problem with Gradle. Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0 is just a warning. 

I'm not sure which version of the library you are using. The latest version of the library didn't work for me. I'm using version `1.1.1`. I faced the same problem as you for missing AwemeOpenSDK library files. You can try to add a single line of code in `android/build.gradle` file. 

```
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        // add this following like
        maven { url "https://artifact.bytedance.com/repository/AwemeOpenSDK" }
```
